---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: janov-os
# description will be included in the image's metadata
description: Janov911 OS Image - my personal OS.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: files
    files:
      - source: files/default.jpg
        destination: usr/share/backgrounds/default.jpg

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - stow
        - ansible
        - asciiquarium
        - autojump
        - aerc
        - bat
        - clamav
        - clamd
        - cmatrix
        - dbus-devel
        - eureka
        - eza
        - fd-find
        - feh
        - firejail
        - fzf
        - git-crypt
        - gnome-boxes
        - gnome-tweaks
        - gnome-directory-thumbnailer
        - gparted
        - httpie
        - irssi
        - kitty
        - konsole
        - libvirt
        - lolcat
        - lsd
        - lua
        - ncdu
        - neovim
        - neomutt
        - newsboat
        - nextcloud-client
        - nvtop
        - pcre
        - podman-compose
        - podman-docker
        - ranger
        - ripgrep
        - smartmontools
        - tailscale
        - task
        - taskopen
        - tealdeer
        - trash-cli
        - unbound
        - vit
        - virt-manager
        - virt-viewer
        - zoxide
    #remove:
      #packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        #- firefox
        #- firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
        - app.zen_browser.zen
        - com.github.rafostar.Clapper.Enhancers
        - com.github.tchx84.Flatseal
        - com.github.zocker_160.SyncThingy
        - com.moonlight_stream.Moonlight
        - com.nextcloud.desktopclient.nextcloud
        - com.play0ad.zeroad
        - com.protonvpn.www
        - com.shatteredpixel.shatteredpixeldungeon
        - com.thincast.client
        - com.valvesoftware.SteamLink
        - dev.geopjr.Tuba
        - dev.ibrahimcetin.reins
        - eu.betterbird.Betterbird
        - im.riot.Riot
        - io.github.fastrizwaan.WineZGUI
        - io.github.fsobolev.TimeSwitch
        - io.github.giantpinkrobots.flatsweep
        - io.github.lo2dev.Echo
        - io.github.vikdevelop.SaveDesktop
        - io.gitlab.news_flash.NewsFlash
        - io.mrarm.mcpelauncher
        - it.mijorus.collector
        - it.mijorus.gearlever
        - net.davidotek.pupgui2
        - net.lutris.Lutris
        - net.newpipe.NewPipe
        - net.openra.OpenRA
        - net.retrodeck.retrodeck
        - org.gnome.Boxes
        - org.gnome.DejaDup
        - org.kde.kdenlive
        - org.nickvision.tubeconverter
        - org.winehq.Wine.gecko
        - org.winehq.Wine.mono        
     # - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
